# Generated by Django 2.2 on 2022-11-18 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36, unique=True, verbose_name='Имя клиента')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36, verbose_name='Название организации')),
                ('address', models.CharField(blank=True, max_length=36, verbose_name='Адрес')),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'organization',
                'verbose_name_plural': 'organizations',
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('bill_sum', models.PositiveIntegerField(verbose_name='Сумма счета')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('service', models.CharField(max_length=36, verbose_name='Наименование услуги')),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Client', verbose_name='Клиент')),
                ('client_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'bill',
                'verbose_name_plural': 'bills',
            },
        ),
    ]
