# Generated by Django 2.2 on 2022-11-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36, unique=True, verbose_name='Наименование услуги')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
            },
        ),
        migrations.RemoveField(
            model_name='bill',
            name='service',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='address',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='client_name',
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_number',
            field=models.CharField(max_length=10, null=True, verbose_name='Номер счета'),
        ),
        migrations.AddField(
            model_name='client',
            name='organizations',
            field=models.ManyToManyField(related_name='clients', to='api.Organization', verbose_name='Организации'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateField(verbose_name='Счет от'),
        ),
        migrations.AddField(
            model_name='bill',
            name='services',
            field=models.ManyToManyField(related_name='bills', to='api.Service', verbose_name='Услуга(и)'),
        ),
    ]
